package ceui.pixiv.ui.common


import android.content.Context
import android.util.Log
import android.view.View
import android.view.ViewGroup
import androidx.lifecycle.LifecycleOwner
import androidx.recyclerview.widget.DiffUtil
import androidx.recyclerview.widget.ListAdapter
import androidx.recyclerview.widget.RecyclerView
import androidx.viewbinding.ViewBinding

val listItemHolderDiffUtil = object :
    DiffUtil.ItemCallback<ListItemHolder>() {
    override fun areItemsTheSame(
        oldItem: ListItemHolder,
        newItem: ListItemHolder
    ): Boolean {
        return oldItem.areItemsTheSame(newItem)
    }

    override fun areContentsTheSame(
        oldItem: ListItemHolder,
        newItem: ListItemHolder
    ): Boolean {
        return oldItem.areContentsTheSame(newItem)
    }
}


// 使用反射获取生成的 ViewHolderFactory，避免 KSP 生成代码未完成时的编译错误
private val viewHolderMap: Map<Int, (ViewGroup) -> ListItemViewHolder<ViewBinding, ListItemHolder>> by lazy {
    try {
        val clazz = Class.forName("ceui.pixiv.ui.viewholdermap.ViewHolderFactory")
        val field = clazz.getDeclaredField("VIEW_HOLDER_MAP")
        field.isAccessible = true
        @Suppress("UNCHECKED_CAST")
        field.get(null) as Map<Int, (ViewGroup) -> ListItemViewHolder<ViewBinding, ListItemHolder>>
    } catch (e: Exception) {
        Log.e("CommonAdapter", "ViewHolderFactory not found, check if KSP is working: ${e.message}")
        emptyMap()
    }
}


class CommonAdapter(private val viewLifecycleOwner: LifecycleOwner) :
    ListAdapter<ListItemHolder, ListItemViewHolder<ViewBinding, ListItemHolder>>(
        listItemHolderDiffUtil
    ) {
    override fun onCreateViewHolder(
        parent: ViewGroup,
        viewType: Int
    ): ListItemViewHolder<ViewBinding, ListItemHolder> {
        val autoGeneratedBuilder = viewHolderMap[viewType]
        if (autoGeneratedBuilder == null) {
            throw RuntimeException("ViewHolderFactory missing entry for viewType: $viewType, check if KSP is working")
        } else {
            return autoGeneratedBuilder.invoke(parent)
        }
    }

    override fun onBindViewHolder(
        holder: ListItemViewHolder<ViewBinding, ListItemHolder>,
        position: Int
    ) {
        val item = getItem(position)
        holder.lifecycleOwner = viewLifecycleOwner
        holder.onBindViewHolder(item, position)
    }

    override fun getItemViewType(position: Int): Int {
        return getItem(position).getItemViewType() // use layout id to unique the item type
    }

    override fun getItemId(position: Int): Long {
        return getItem(position).getItemId()
    }
}

open class ListItemHolder {


    open fun areItemsTheSame(other: ListItemHolder): Boolean {
        return if (this.getItemId() != 0L || other.getItemId() != 0L) {
            this.getItemId() == other.getItemId()
        } else {
            this === other
        }
    }

    open fun areContentsTheSame(other: ListItemHolder): Boolean {
        return this == other
    }

    fun getItemViewType(): Int {
        return this::class.java.name.hashCode()
    }

    open fun getItemId(): Long {
        return 0L
    }

    private var _onItemClick: ((View) -> Unit)? = null

    open fun onItemClick(block: (View) -> Unit): ListItemHolder {
        _onItemClick = block
        return this
    }

    fun retrieveClickListener(): ((View) -> Unit)? {
        return _onItemClick
    }
}

open class ListItemViewHolder<Binding : ViewBinding, T : ListItemHolder>(val binding: Binding) :
    RecyclerView.ViewHolder(binding.root) {

    protected val context: Context = binding.root.context
    lateinit var lifecycleOwner: LifecycleOwner

    open fun onBindViewHolder(item: T, position: Int) {
        val listener = item.retrieveClickListener()
        if (listener != null) {
            binding.root.setOnClickListener { sender ->
                try {
                    listener(sender)
                } catch (ex: Exception) {
                    Log.e(TAG, "onItemClick error", ex)
                }
            }
        } else {
            binding.root.setOnClickListener(null)
        }
    }


    companion object {
        private const val TAG = "CommonAdapter"
    }
}