plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.navigation.safeargs)
    alias(libs.plugins.ksp)
}

android {
    compileSdk Integer.parseInt(project.property("COMPILE_SDK"))

    defaultConfig {
        applicationId "ceui.pixiv"
        minSdk Integer.parseInt(project.property("MIN_SDK"))
        targetSdk Integer.parseInt(project.property("TARGET_SDK"))
        versionCode 40580
        versionName "4.6.4"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        resConfigs "zh-rCN", "zh-rTW", "zh-rHK", "en", "ja", "ko", "ru", "tr"
        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    lint {
        abortOnError false
    }

    signingConfigs {
        debug {
            storeFile file("../keystore.jks")
            storePassword "123456"
            keyAlias 'CeuiLiSA'
            keyPassword '123456'
        }

        release {
            storeFile file("../keystore.jks")
            storePassword "123456"
            keyAlias 'CeuiLiSA'
            keyPassword '123456'
        }
    }

    flavorDimensions += "channel"
    productFlavors {
        google {
            dimension "channel"
            buildConfigField "String", "UPDATE_CHANNEL", '"google"'
        }
        github {
            dimension "channel"
            buildConfigField "String", "UPDATE_CHANNEL", '"github"'
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
            buildConfigField "boolean", "IS_DEBUG_MODE", "true"
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release

            applicationIdSuffix ".cshaft"
            resValue "string", "app_name", "Shaft(Debug)"
        }
        release {
            minifyEnabled true
            shrinkResources true
            buildConfigField "boolean", "IS_DEBUG_MODE", "false"
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release

            applicationIdSuffix ".pshaft"
            resValue "string", "app_name", "Shaft"
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
        buildConfig = true
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
        resources {
            excludes += ['META-INF/MANIFEST.MF', 'META-INF/gradle/incremental.annotation.processors']
        }
    }

    namespace 'ceui.lisa'
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    testImplementation libs.junit
    androidTestImplementation libs.test.ext.junit
    androidTestImplementation libs.espresso.core

    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.recyclerview
    implementation libs.material

    implementation libs.bundles.lifecycle
    implementation libs.bundles.navigation

    implementation libs.kotlin.stdlib
    implementation libs.core.ktx
    implementation libs.bundles.coroutines

    api libs.bundles.retrofit

    implementation project(":annotations")
    ksp project(":processor")

    implementation libs.bundles.glide
    ksp libs.glide.ksp

    implementation libs.bundles.refresh

    implementation libs.bundles.okhttp

    implementation libs.glide.transformations
    implementation libs.spinkit
    implementation libs.ucrop

    implementation libs.bundles.room
    ksp libs.room.compiler

    implementation libs.html.textview
    implementation libs.qmui
    implementation libs.viewpager.transforms
    implementation libs.recyclerview.animators
    implementation libs.utilcodex

    implementation libs.bundles.review

    implementation libs.colorpicker
    implementation libs.splashscreen

    implementation libs.panel.switch

    implementation libs.cronet.embedded

    implementation libs.lottie

    implementation project(':models')

    implementation libs.webkit
    implementation libs.browser

    implementation libs.pixiv.login
    implementation libs.jsoup

    implementation libs.toast.utils

    implementation libs.documentfile
    implementation libs.markwon.core
    implementation libs.activity.ktx
    implementation libs.flexbox

    implementation libs.zoomimage.view.sketch4
    implementation libs.fastscroll

    implementation libs.work.runtime.ktx

    coreLibraryDesugaring libs.desugar.jdk.libs
}
