plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'kotlin-parcelize'
    id 'androidx.navigation.safeargs.kotlin'
    id 'com.google.devtools.ksp'
}

android {
    compileSdk rootProject.ext.compile_sdk

    defaultConfig {
        applicationId "ceui.pixiv"
        minSdkVersion rootProject.ext.min_sdk
        targetSdkVersion rootProject.ext.target_sdk
        versionCode 40580
        versionName "4.6.4"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        resConfigs "zh-rCN", "zh-rTW", "zh-rHK", "en", "ja", "ko", "ru", "tr"
        ndk {
            abiFilters 'arm64-v8a'
        }

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [:]
            }
        }
    }

    lint {
        abortOnError false
    }

    signingConfigs {
        debug {
            storeFile file("../keystore.jks")
            storePassword "123456"
            keyAlias 'CeuiLiSA'
            keyPassword '123456'
        }

        release {
            storeFile file("../keystore.jks")
            storePassword "123456"
            keyAlias 'CeuiLiSA'
            keyPassword '123456'
        }
    }

    flavorDimensions += "channel"
    productFlavors {
        google {
            dimension "channel"
            buildConfigField "String", "UPDATE_CHANNEL", '"google"'
        }
        github {
            dimension "channel"
            buildConfigField "String", "UPDATE_CHANNEL", '"github"'
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
            buildConfigField "boolean", "IS_DEBUG_MODE", "true"
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release

            applicationIdSuffix ".cshaft"
            resValue "string", "app_name", "Shaft(Debug)"
        }
        release {
            minifyEnabled true
            shrinkResources true
            buildConfigField "boolean", "IS_DEBUG_MODE", "false"
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release

            applicationIdSuffix ".pshaft"
            resValue "string", "app_name", "Shaft"
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        dataBinding true
        viewBinding true
        buildConfig = true
    }
    
    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
        resources {
            excludes += ['META-INF/MANIFEST.MF', 'META-INF/gradle/incremental.annotation.processors']
        }
    }

    namespace 'ceui.lisa'
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
    androidTestImplementation "androidx.test.ext:junit:1.2.1"
    androidTestImplementation "androidx.test.espresso:espresso-core:3.6.1"

    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'com.google.android.material:material:1.12.0'

    // LifeCycle
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:${rootProject.ext.lifecycle_version}"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:${rootProject.ext.lifecycle_version}"

    // Navigation
    implementation "androidx.navigation:navigation-fragment-ktx:${rootProject.ext.nav_version}"
    implementation "androidx.navigation:navigation-ui-ktx:${rootProject.ext.nav_version}"

    implementation "org.jetbrains.kotlin:kotlin-stdlib:${rootProject.ext.kotlin_version}"
    implementation "androidx.core:core-ktx:${rootProject.ext.core_ktx_version}"

    // Network
    api "com.squareup.retrofit2:retrofit:${rootProject.ext.retrofit_version}"
    api "com.squareup.retrofit2:converter-gson:${rootProject.ext.retrofit_version}"
    api 'com.squareup.retrofit2:adapter-rxjava2:2.9.0'

    api 'io.reactivex.rxjava2:rxjava:2.2.21'
    api 'io.reactivex.rxjava2:rxandroid:2.1.1'

    implementation project(":annotations")
    implementation project(":processor")
    kapt project(":processor")

    // Image Loading
    implementation "com.github.bumptech.glide:glide:${rootProject.ext.glide_version}"
    implementation "com.github.bumptech.glide:okhttp3-integration:${rootProject.ext.glide_version}"
    ksp "com.github.bumptech.glide:compiler:${rootProject.ext.glide_version}"

    def refresh_version = "2.1.0"
    implementation "io.github.scwang90:refresh-layout-kernel:$refresh_version"
    implementation "io.github.scwang90:refresh-header-classics:$refresh_version"
    implementation "io.github.scwang90:refresh-header-falsify:$refresh_version"
    implementation "io.github.scwang90:refresh-header-material:$refresh_version"
    implementation "io.github.scwang90:refresh-footer-classics:$refresh_version"

    implementation "com.squareup.okhttp3:logging-interceptor:${rootProject.ext.okhttp_version}"
    implementation 'jp.wasabeef:glide-transformations:4.3.0'
    implementation 'com.github.ybq:Android-SpinKit:1.4.0'
    implementation 'com.github.yalantis:ucrop:2.2.8'
    
    // Room
    implementation "androidx.room:room-runtime:${rootProject.ext.room_version}"
    implementation "androidx.room:room-ktx:${rootProject.ext.room_version}"
    ksp "androidx.room:room-compiler:${rootProject.ext.room_version}"
    
    implementation "org.sufficientlysecure:html-textview:4.0"
    implementation 'com.qmuiteam:qmui:2.0.1'
    implementation 'com.ToxicBakery.viewpager.transforms:view-pager-transforms:2.0.24'
    implementation 'jp.wasabeef:recyclerview-animators:4.0.2'
    implementation 'com.blankj:utilcodex:1.31.1'

    implementation 'com.google.android.play:review:2.0.2'
    implementation 'com.google.android.play:review-ktx:2.0.2'

    implementation 'com.jaredrummler:colorpicker:1.1.0'
    implementation 'androidx.core:core-splashscreen:1.0.1'

    implementation 'com.effective.android:panelSwitchHelper-androidx:1.3.13'

    implementation "com.squareup.okhttp3:okhttp:${rootProject.ext.okhttp_version}"

    implementation 'org.chromium.net:cronet-embedded:143.7445.0'

    // RxJava 3
    implementation "io.reactivex.rxjava3:rxjava:${rootProject.ext.rxjava3_version}"
    implementation "io.reactivex.rxjava3:rxandroid:${rootProject.ext.rxandroid3_version}"
    implementation 'com.github.liujingxing.rxlife:rxlife-rxjava3:2.2.2'

    implementation "com.airbnb.android:lottie:6.7.1"

    implementation project(':models')
    implementation project(':progressmanager')
    implementation project(':flowlayout-lib')

    implementation 'androidx.webkit:webkit:1.12.1'
    implementation 'androidx.browser:browser:1.8.0'

    implementation 'com.github.SoxiaLiSA:pixiv-login:1.2.0'
    implementation 'org.jsoup:jsoup:1.18.1'

    implementation 'com.github.getActivity:ToastUtils:12.6'

    implementation "androidx.documentfile:documentfile:1.0.1"
    implementation "io.noties.markwon:core:4.6.2"
    implementation "androidx.activity:activity-ktx:${rootProject.ext.activity_ktx_version}"
    implementation "com.google.android.flexbox:flexbox:3.0.0"

    implementation "io.github.panpf.zoomimage:zoomimage-view-sketch4:1.4.0"
    implementation "me.zhanghai.android.fastscroll:library:1.2.0"

    implementation "androidx.work:work-runtime-ktx:${rootProject.ext.work_version}"

    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:${rootProject.ext.desugar_version}"
}
