plugins {
    id 'com.android.library'
}

android {
    compileSdk rootProject.ext.compile_sdk

    defaultConfig {
        minSdkVersion rootProject.ext.min_sdk
        targetSdkVersion rootProject.ext.target_sdk

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lint {
        abortOnError false
        warning 'InvalidPackage'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    namespace 'me.jessyan.progressmanager'
}

dependencies {
    compileOnly "com.squareup.okhttp3:okhttp:${rootProject.ext.okhttp_version}"
}
